"""Load and validate a consumer's ``workflow.toml``.

The file is read by humans, agents and this package. This skeleton validates
``[hooks]`` commands but does not execute them; privileged hooks are read from
the approved base revision through :func:`hooks_from_base`, never from the
candidate worktree. Validation reports every problem at once so a consumer
fixes the file in one pass.
"""

from __future__ import annotations

import os
import re
import stat
import subprocess
import tomllib
import unicodedata
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

WORKFLOW_FILE = "workflow.toml"
CONTRACT_ID = "loop-zero-v1"
PROFILES = ("python", "fastapi", "nextjs", "angular")
RUNNERS = ("claude", "codex", "cursor", "acp", "fake")
EFFORTS = ("low", "medium", "high", "xhigh", "max")
SANDBOXES = ("bwrap",)
CHECK_GROUPS = ("required", "advisory", "scheduled")
HOOK_NAMES = ("worktree_setup", "acceptance", "db_acceptance", "closeout")
PRIVILEGED_HOOKS = ("acceptance", "db_acceptance", "closeout")
MANAGED_BLOCK_BEGIN = "<!-- loopzero:begin generated by `loopzero sync`; do not edit inside -->"
MANAGED_BLOCK_END = "<!-- loopzero:end -->"
MANAGED_MARKER_TOKENS = ("loopzero:begin", "loopzero:end")

_SHA_RE = re.compile(r"^[0-9a-f]{40}$")
_HEX_SHA_RE = re.compile(r"^[0-9a-f]{40}$", re.IGNORECASE)
_PREFIX_RE = re.compile(r"^[A-Z][A-Z0-9_]*$")
_ALIAS_RE = re.compile(r"^[a-z][a-z0-9-]{0,31}$")
_BASE_REF_RE = re.compile(
    r"^refs/(?:heads/[A-Za-z0-9][A-Za-z0-9._/-]*|"
    r"remotes/[A-Za-z0-9][A-Za-z0-9._-]*/[A-Za-z0-9][A-Za-z0-9._/-]*)$"
)


class ConfigError(ValueError):
    """Raised with every validation problem joined by newlines."""

    def __init__(self, problems: list[str]):
        self.problems = list(problems)
        super().__init__("\n".join(self.problems))


@dataclass(frozen=True)
class Alias:
    runner: str
    model: str
    write: bool = False
    agent: str | None = None


@dataclass(frozen=True)
class Tier:
    alias: str
    effort: str = "medium"
    read_only: bool = False


@dataclass(frozen=True)
class Profile:
    """Validated view of ``workflow.toml``. Paths are relative to ``root``."""

    root: Path
    core_repository: str
    core_revision: str
    core_path: Path
    profiles: tuple[str, ...]
    checks: dict[str, tuple[str, ...]]
    env_prefix: str = "LOOPZERO"
    audit_root: Path = Path(".audit")
    state_root: str = "~/.local/state/loopzero"
    contract: str = CONTRACT_ID
    epoch: int = 1
    sandbox: str = "bwrap"
    toolchain: dict[str, Any] = field(default_factory=dict)
    aliases: dict[str, Alias] = field(default_factory=dict)
    tiers: dict[str, Tier] = field(default_factory=dict)
    max_reviews_per_pr: int = 1
    max_delta_reviews: int = 1
    required_sections: tuple[str, ...] = ()
    native_protection: bool = True
    path_classes: dict[str, tuple[str, ...]] = field(default_factory=dict)
    hooks: dict[str, tuple[str, ...]] = field(default_factory=dict)
    raw: dict[str, Any] = field(default_factory=dict, repr=False)

    @property
    def snapshot_dir(self) -> Path:
        return self.root / self.core_path

    def snapshot_version(self) -> str | None:
        version_file = self.snapshot_dir / "VERSION"
        try:
            if not stat.S_ISREG(os.lstat(version_file).st_mode):
                return None
            return version_file.read_text(encoding="utf-8").strip()
        except FileNotFoundError:
            return None
        except (OSError, UnicodeError) as exc:
            raise ConfigError([f"{version_file}: cannot read snapshot version: {exc}"]) from None


def load_mapping(path: Path) -> dict[str, Any]:
    try:
        with path.open("rb") as handle:
            return tomllib.load(handle)
    except FileNotFoundError:
        raise ConfigError([f"{path}: missing"]) from None
    except (tomllib.TOMLDecodeError, UnicodeError) as exc:
        raise ConfigError([f"{path}: invalid TOML: {exc}"]) from None
    except OSError as exc:
        raise ConfigError([f"{path}: cannot read: {exc}"]) from None


def _commands(value: Any, where: str, problems: list[str]) -> tuple[str, ...]:
    if isinstance(value, str):
        return (value,) if value.strip() else _fail(problems, f"{where}: empty command")
    if isinstance(value, list) and all(isinstance(item, str) and item.strip() for item in value):
        return tuple(value)
    return _fail(problems, f"{where}: must be a string or a list of nonempty strings")


def _fail(problems: list[str], message: str) -> tuple[str, ...]:
    problems.append(message)
    return ()


def _reject_unsafe_rendered_string(value: Any, where: str, problems: list[str]) -> bool:
    """Reject text that can change the structure of a generated file."""
    if not isinstance(value, str):
        return False
    valid = True
    if any(unicodedata.category(character) == "Cc" for character in value):
        problems.append(f"{where}: control characters are forbidden")
        valid = False
    if any(marker in value for marker in MANAGED_MARKER_TOKENS):
        problems.append(f"{where}: managed-block marker text is forbidden")
        valid = False
    return valid


def _hooks(data: dict[str, Any], where: str, problems: list[str]) -> dict[str, tuple[str, ...]]:
    """Validate hooks identically for candidate and committed base policy."""
    hooks: dict[str, tuple[str, ...]] = {}
    hooks_table = data.get("hooks", {})
    if not isinstance(hooks_table, dict):
        problems.append(f"{where}: must be a table")
        return hooks
    for name, value in hooks_table.items():
        item_where = f"{where}.{name}"
        if name not in HOOK_NAMES:
            problems.append(
                f"{item_where}: unknown hook; known hooks are {', '.join(HOOK_NAMES)}"
            )
            continue
        commands = _commands(value, item_where, problems)
        if commands:
            hooks[name] = commands
    return hooks


def validate(data: dict[str, Any], root: Path) -> Profile:
    """Return a :class:`Profile` or raise :class:`ConfigError` listing every problem."""
    problems: list[str] = []

    core = data.get("core")
    if not isinstance(core, dict):
        problems.append("[core]: missing table")
        core = {}
    repository = core.get("repository")
    revision = core.get("revision")
    core_path = core.get("path")
    if not isinstance(repository, str) or not repository.strip():
        problems.append("[core].repository: must be a nonempty string")
    else:
        _reject_unsafe_rendered_string(repository, "[core].repository", problems)
    if not isinstance(revision, str) or not _SHA_RE.match(revision):
        problems.append("[core].revision: must be a full 40-character lowercase commit SHA")
    if (
        not isinstance(core_path, str)
        or not core_path.strip()
        or Path(core_path).is_absolute()
        or not Path(core_path).parts
        or ".." in Path(core_path).parts
    ):
        problems.append("[core].path: must be a nonempty repository-relative path without traversal")
    else:
        _reject_unsafe_rendered_string(core_path, "[core].path", problems)
        current = Path(os.path.abspath(root))
        for part in Path(core_path).parts:
            current = current / part
            try:
                if stat.S_ISLNK(os.lstat(current).st_mode):
                    problems.append(f"[core].path: symlink component {current} is forbidden")
                    break
            except FileNotFoundError:
                problems.append(f"[core].path: component {current} does not exist")
                break
            except OSError as exc:
                problems.append(f"[core].path: cannot inspect {current}: {exc}")
                break

    profiles = data.get("profiles", [])
    if not isinstance(profiles, list) or any(p not in PROFILES for p in profiles):
        problems.append(f"profiles: must be a list drawn from {', '.join(PROFILES)}")
        profiles = []

    checks_table = data.get("checks")
    checks: dict[str, tuple[str, ...]] = {}
    if not isinstance(checks_table, dict):
        problems.append("[checks]: missing table with required, advisory and scheduled arrays")
    else:
        seen: set[str] = set()
        for group in CHECK_GROUPS:
            names = checks_table.get(group)
            if not isinstance(names, list):
                problems.append(f"[checks].{group}: must be an array of exact check names")
                continue
            for name in names:
                if not isinstance(name, str) or not name.strip():
                    problems.append(f"[checks].{group}: check names must be nonempty strings")
                elif name in seen:
                    problems.append(f"[checks]: {name!r} appears in more than one group")
                seen.add(name if isinstance(name, str) else "")
            checks[group] = tuple(n for n in names if isinstance(n, str))

    package = data.get("package", {})
    if not isinstance(package, dict):
        problems.append("[package]: must be a table")
        package = {}
    env_prefix = package.get("env_prefix", "LOOPZERO")
    if not isinstance(env_prefix, str) or not _PREFIX_RE.match(env_prefix):
        problems.append("[package].env_prefix: must match [A-Z][A-Z0-9_]*")
    audit_root = package.get("audit_root", ".audit")
    if not isinstance(audit_root, str) or Path(audit_root).is_absolute():
        problems.append("[package].audit_root: must be a relative path")
    state_root = package.get("state_root", "~/.local/state/loopzero")
    if not isinstance(state_root, str) or not state_root:
        problems.append("[package].state_root: must be a nonempty path")
    contract = package.get("contract", CONTRACT_ID)
    if contract != CONTRACT_ID:
        problems.append(f"[package].contract: must be {CONTRACT_ID!r}")
    epoch = package.get("epoch", 1)
    if type(epoch) is not int or epoch < 1:
        problems.append("[package].epoch: must be a positive integer")
    sandbox = package.get("sandbox", "bwrap")
    if sandbox not in SANDBOXES:
        problems.append(f"[package].sandbox: must be one of {', '.join(SANDBOXES)}")

    toolchain = data.get("toolchain", {})
    if not isinstance(toolchain, dict):
        problems.append("[toolchain]: must be a table")
        toolchain = {}

    routing = data.get("routing", {})
    aliases: dict[str, Alias] = {}
    tiers: dict[str, Tier] = {}
    if not isinstance(routing, dict):
        problems.append("[routing]: must be a table")
    else:
        aliases_table = routing.get("aliases", {})
        if not isinstance(aliases_table, dict):
            problems.append("[routing.aliases]: must be a table")
            aliases_table = {}
        for name, spec in aliases_table.items():
            where = f"[routing.aliases].{name}"
            if not _ALIAS_RE.match(str(name)):
                problems.append(f"{where}: alias names match [a-z][a-z0-9-]*")
            if not isinstance(spec, dict):
                problems.append(f"{where}: must be a table")
                continue
            unknown = spec.keys() - {"runner", "model", "write", "agent"}
            for field_name in sorted(unknown):
                problems.append(f"{where}.{field_name}: unknown field")
            runner = spec.get("runner")
            model = spec.get("model")
            write = spec.get("write", False)
            agent = spec.get("agent")
            valid = True
            if runner not in RUNNERS:
                problems.append(f"{where}: runner must be one of {', '.join(RUNNERS)}")
                valid = False
            if not isinstance(model, str) or not model:
                problems.append(f"{where}: model must be a nonempty string")
                valid = False
            if not isinstance(write, bool):
                problems.append(f"{where}.write: must be a boolean")
                valid = False
            if agent is not None and not isinstance(agent, str):
                problems.append(f"{where}.agent: must be a string or absent")
                valid = False
            if valid:
                aliases[name] = Alias(runner=runner, model=model, write=write, agent=agent)

        tiers_table = routing.get("tiers", {})
        if not isinstance(tiers_table, dict):
            problems.append("[routing.tiers]: must be a table")
            tiers_table = {}
        for name, spec in tiers_table.items():
            where = f"[routing.tiers].{name}"
            if not isinstance(spec, dict):
                problems.append(f"{where}: must be a table")
                continue
            unknown = spec.keys() - {"alias", "effort", "read_only"}
            for field_name in sorted(unknown):
                problems.append(f"{where}.{field_name}: unknown field")
            alias = spec.get("alias")
            effort = spec.get("effort", "medium")
            read_only = spec.get("read_only", False)
            valid = True
            if not isinstance(alias, str) or alias not in aliases:
                problems.append(f"{where}: alias must name an entry in [routing.aliases]")
                valid = False
            if not isinstance(effort, str) or effort not in EFFORTS:
                problems.append(f"{where}.effort: must be one of {', '.join(EFFORTS)}")
                valid = False
            if not isinstance(read_only, bool):
                problems.append(f"{where}.read_only: must be a boolean")
                valid = False
            if valid:
                tiers[name] = Tier(alias=alias, effort=effort, read_only=read_only)

    review = data.get("review", {})
    if not isinstance(review, dict):
        problems.append("[review]: must be a table")
        review = {}
    max_reviews = review.get("max_reviews_per_pr", 1)
    max_delta = review.get("max_delta_reviews", 1)
    for label, value in (("max_reviews_per_pr", max_reviews), ("max_delta_reviews", max_delta)):
        if type(value) is not int or value < 0:
            problems.append(f"[review].{label}: must be a non-negative integer")
    sections = review.get("required_sections", [])
    if not isinstance(sections, list) or any(not isinstance(s, str) for s in sections):
        problems.append("[review].required_sections: must be a list of strings")
        sections = []

    github = data.get("github", {})
    if not isinstance(github, dict):
        problems.append("[github]: must be a table")
        github = {}
    native_protection = github.get("native_protection", True)
    if not isinstance(native_protection, bool):
        problems.append("[github].native_protection: must be a boolean")

    path_classes: dict[str, tuple[str, ...]] = {}
    path_classes_table = data.get("path_classes", {})
    if not isinstance(path_classes_table, dict):
        problems.append("[path_classes]: must be a table")
        path_classes_table = {}
    for name, globs in path_classes_table.items():
        if not isinstance(globs, list) or any(not isinstance(g, str) or not g for g in globs):
            problems.append(f"[path_classes].{name}: must be a list of glob strings")
            continue
        path_classes[str(name)] = tuple(globs)

    hooks = _hooks(data, "[hooks]", problems)

    if problems:
        raise ConfigError(problems)

    return Profile(
        root=root,
        core_repository=repository,
        core_revision=revision,
        core_path=Path(core_path),
        profiles=tuple(profiles),
        checks=checks,
        env_prefix=env_prefix,
        audit_root=Path(audit_root),
        state_root=state_root,
        contract=contract,
        epoch=epoch,
        sandbox=sandbox,
        toolchain=dict(toolchain),
        aliases=aliases,
        tiers=tiers,
        max_reviews_per_pr=max_reviews,
        max_delta_reviews=max_delta,
        required_sections=tuple(sections),
        native_protection=native_protection,
        path_classes=path_classes,
        hooks=hooks,
        raw=data,
    )


def load_profile(root: Path) -> Profile:
    """Load and validate ``<root>/workflow.toml``."""
    root = Path(os.path.abspath(root))
    return validate(load_mapping(root / WORKFLOW_FILE), root)


def _git(root: Path, *args: str) -> subprocess.CompletedProcess[str]:
    environment = {
        "PATH": "/usr/bin:/bin",
        "GIT_CONFIG_GLOBAL": os.devnull,
        "GIT_CONFIG_NOSYSTEM": "1",
        "GIT_NO_REPLACE_OBJECTS": "1",
        "GIT_TERMINAL_PROMPT": "0",
    }
    return subprocess.run(
        ["git", "-C", str(root), *args],
        capture_output=True,
        text=True,
        encoding="utf-8",
        env=environment,
    )


def _absolute_directory_no_follow(path: Path, label: str) -> Path:
    """Return an absolute directory path only when every component is real."""
    absolute = Path(os.path.abspath(path))
    current = Path(absolute.anchor)
    try:
        for part in absolute.parts[1:]:
            current /= part
            metadata = os.lstat(current)
            if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISDIR(metadata.st_mode):
                raise ConfigError(
                    [f"{label} {absolute}: contains a symlink or non-directory component"]
                )
    except FileNotFoundError:
        raise ConfigError([f"{label} {absolute}: does not exist"]) from None
    except OSError as exc:
        raise ConfigError([f"{label} {absolute}: cannot inspect without following links: {exc}"]) from None
    return absolute


def _require_git_toplevel(root: Path) -> Path:
    root = _absolute_directory_no_follow(root, "consumer root")
    proc = _git(root, "rev-parse", "--show-toplevel")
    if proc.returncode != 0:
        detail = proc.stderr.strip() or "not a Git repository"
        raise ConfigError([f"consumer root {root}: cannot determine Git top level ({detail})"])
    output = proc.stdout.strip()
    if not output:
        raise ConfigError([f"consumer root {root}: Git returned an empty top level"])
    top_level = _absolute_directory_no_follow(Path(output), "Git top level")
    if root != top_level:
        raise ConfigError(
            [f"consumer root {root}: must equal Git top level {top_level}"]
        )
    return root


def resolve_base(root: Path, *, base: str | None = None, base_ref: str | None = None) -> str:
    """Resolve and verify one explicit trusted base selection to a commit SHA."""
    if (base is None) == (base_ref is None):
        raise ConfigError(["select exactly one of --base or --base-ref"])
    if base is not None and not _HEX_SHA_RE.fullmatch(base):
        raise ConfigError(["--base must be a full 40-character hexadecimal commit SHA"])
    if base_ref is not None and (
        not _BASE_REF_RE.fullmatch(base_ref)
        or ".." in base_ref
        or "//" in base_ref
        or base_ref.endswith(("/", "."))
        or any(part.startswith(".") or part.endswith(".lock") for part in base_ref.split("/"))
    ):
        raise ConfigError(
            [
                "--base-ref must be a full named ref under refs/heads/<branch> "
                "or refs/remotes/<remote>/<branch>"
            ]
        )
    requested = base if base is not None else base_ref
    root = _require_git_toplevel(root)
    if base_ref is not None:
        ref_proc = _git(root, "show-ref", "--verify", base_ref)
        if ref_proc.returncode != 0:
            detail = ref_proc.stderr.strip() or "named ref is unavailable"
            raise ConfigError([f"base {base_ref!r}: unavailable ({detail})"])
    proc = _git(root, "rev-parse", "--verify", "--end-of-options", f"{requested}^{{commit}}")
    sha = proc.stdout.strip()
    if proc.returncode != 0 or not _SHA_RE.fullmatch(sha):
        detail = proc.stderr.strip() or "does not identify an available commit"
        raise ConfigError([f"base {requested!r}: unavailable ({detail})"])
    if base is not None and sha != base.lower():
        raise ConfigError([f"--base {base}: did not resolve to that exact commit"])
    return sha


def hooks_from_base(root: Path, base_sha: str) -> dict[str, tuple[str, ...]]:
    """Return the validated ``[hooks]`` table committed at ``base_sha``.

    Privileged hooks come from the approved base, so a candidate cannot change
    its own acceptance command before that change is merged. Raises
    :class:`ConfigError` when the base revision or its file is unavailable;
    callers must treat that as a blocker, never as "no hooks".
    """
    root = Path(os.path.abspath(root))
    sha = resolve_base(root, base=base_sha)
    tree = _git(root, "ls-tree", "--full-tree", sha, "--", WORKFLOW_FILE)
    if tree.returncode != 0:
        raise ConfigError([f"{WORKFLOW_FILE} at {sha}: unavailable ({tree.stderr.strip()})"])
    fields = tree.stdout.rstrip("\n").split(None, 3)
    if len(fields) != 4 or fields[0] not in ("100644", "100755") or fields[1] != "blob":
        raise ConfigError([f"{WORKFLOW_FILE} at {sha}: must be a regular blob"])
    try:
        proc = _git(root, "cat-file", "-p", f"{sha}:{WORKFLOW_FILE}")
    except UnicodeError as exc:
        raise ConfigError([f"{WORKFLOW_FILE} at {sha}: is not UTF-8 ({exc})"]) from None
    if proc.returncode != 0:
        raise ConfigError([f"{WORKFLOW_FILE} at {sha}: unavailable ({proc.stderr.strip()})"])
    try:
        data = tomllib.loads(proc.stdout)
    except tomllib.TOMLDecodeError as exc:
        raise ConfigError([f"{WORKFLOW_FILE} at {sha}: invalid TOML: {exc}"]) from None
    problems: list[str] = []
    hooks = _hooks(data, f"[hooks] at {sha}", problems)
    if problems:
        raise ConfigError(problems)
    return hooks


def effective_hooks(profile: Profile, base_sha: str) -> dict[str, tuple[str, ...]]:
    """Merge candidate and base hooks: privileged names always come from the base."""
    base = hooks_from_base(profile.root, base_sha)
    merged = dict(profile.hooks)
    for name in PRIVILEGED_HOOKS:
        if name in base:
            merged[name] = base[name]
        else:
            merged.pop(name, None)
    return merged
