"""Render consumer wiring from ``workflow.toml``.

Generated content is checked in so it stays reviewable. Files a consumer
already owns (``AGENTS.md``, ``CLAUDE.md``) receive one managed block between
markers and are otherwise untouched. Files the package fully owns live under
``.loopzero/`` and ``.cursor/rules/``. ``check`` renders in memory and reports
drift without writing.
"""

from __future__ import annotations

import json
import os
import stat
import tempfile
from dataclasses import dataclass
from pathlib import Path

from .config import ConfigError, Profile

BEGIN = "<!-- loopzero:begin generated by `loopzero sync`; do not edit inside -->"
END = "<!-- loopzero:end -->"


@dataclass(frozen=True)
class Rendered:
    path: Path
    content: str
    managed_block: bool


@dataclass(frozen=True)
class Prepared:
    rendered: Rendered
    target: Path
    original: bytes | None
    expected: bytes


def _pointer_block(profile: Profile, adapter: str) -> str:
    snapshot = profile.core_path.as_posix()
    return (
        f"{BEGIN}\n"
        f"Shared workflow: read `{snapshot}/adapters/{adapter}.md`, then "
        f"`{snapshot}/CONTRACT.md` and `workflow.toml`. Source revision "
        f"`{profile.core_revision}` from {profile.core_repository}. "
        f"Run `loopzero sync --check` before publishing wiring changes.\n"
        f"{END}\n"
    )


def _cursor_rule(profile: Profile) -> str:
    snapshot = profile.core_path.as_posix()
    return (
        "---\n"
        "description: loop-zero shared workflow entry point (generated)\n"
        "alwaysApply: true\n"
        "---\n\n"
        f"Read `{snapshot}/CONTRACT.md` and `workflow.toml` before workflow work. "
        f"Selected profiles: {', '.join(profile.profiles) or 'none'}. "
        f"Source revision `{profile.core_revision}`.\n"
        "One mutable task owns one worktree; acquire the writer lease before "
        "mutating; validation children have no commit authority.\n"
    )


def _claude_settings_fragment(profile: Profile) -> str:
    fragment = {
        "$comment": (
            "generated by `loopzero sync`; merge into .claude/settings.json. "
            "Hook execution is installed by the kernel, not this package skeleton"
        ),
        "hooks": {},
    }
    return json.dumps(fragment, indent=2, sort_keys=True) + "\n"


def _manifest(profile: Profile, files: list[Rendered]) -> str:
    manifest = {
        "core_revision": profile.core_revision,
        "epoch": profile.epoch,
        "generated": sorted(r.path.as_posix() for r in files),
    }
    return json.dumps(manifest, indent=2, sort_keys=True) + "\n"


def render(profile: Profile) -> list[Rendered]:
    files = [
        Rendered(Path("AGENTS.md"), _pointer_block(profile, "codex"), True),
        Rendered(Path("CLAUDE.md"), _pointer_block(profile, "claude"), True),
        Rendered(Path(".cursor/rules/loopzero.mdc"), _cursor_rule(profile), False),
        Rendered(Path(".loopzero/claude-settings-fragment.json"), _claude_settings_fragment(profile), False),
    ]
    files.append(Rendered(Path(".loopzero/generated.json"), _manifest(profile, files), False))
    return files


def _line_value(line: str) -> str:
    if line.endswith("\r\n"):
        return line[:-2]
    if line.endswith(("\r", "\n")):
        return line[:-1]
    return line


def _apply_block(existing: str, block: str, newline: str = "\n") -> str:
    lines = existing.splitlines(keepends=True)
    values = [_line_value(line) for line in lines]
    for value in values:
        if (BEGIN in value and value != BEGIN) or (END in value and value != END):
            raise ConfigError(["managed markers must be exact standalone lines"])
    begins = [index for index, value in enumerate(values) if value == BEGIN]
    ends = [index for index, value in enumerate(values) if value == END]
    if len(begins) != len(ends) or len(begins) not in (0, 1):
        raise ConfigError(["managed markers must contain zero or one matched pair"])
    if begins and begins[0] >= ends[0]:
        raise ConfigError(["managed markers are reversed or malformed"])

    block = block.replace("\n", newline)
    if begins:
        head = "".join(lines[: begins[0]])
        tail = "".join(lines[ends[0] + 1 :]).lstrip("\r\n")
        return head + block + (newline + tail if tail else "")
    if existing and not existing.endswith(("\r", "\n")):
        existing += newline
    return existing + (newline if existing else "") + block


def _safe_target(root: Path, relative: Path) -> Path:
    """Resolve a generated target after lstat-checking every existing component."""
    try:
        root = root.resolve(strict=True)
    except OSError as exc:
        raise ConfigError([f"repository root is unavailable: {exc}"]) from None
    if relative.is_absolute() or not relative.parts or ".." in relative.parts:
        raise ConfigError([f"generated target {relative}: must remain inside the repository"])
    target = root / relative
    try:
        target.resolve(strict=False).relative_to(root)
    except (OSError, ValueError):
        raise ConfigError([f"generated target {relative}: resolves outside the repository"]) from None

    current = root
    missing = False
    for index, part in enumerate(relative.parts):
        current = current / part
        if missing:
            continue
        try:
            metadata = os.lstat(current)
        except FileNotFoundError:
            missing = True
            continue
        except OSError as exc:
            raise ConfigError([f"generated target {relative}: cannot inspect {current}: {exc}"]) from None
        if stat.S_ISLNK(metadata.st_mode):
            raise ConfigError([f"generated target {relative}: symlink component {current} is forbidden"])
        final = index == len(relative.parts) - 1
        if final and not stat.S_ISREG(metadata.st_mode):
            raise ConfigError([f"generated target {relative}: existing target must be a regular file"])
        if not final and not stat.S_ISDIR(metadata.st_mode):
            raise ConfigError([f"generated target {relative}: parent {current} is not a directory"])
    return target


def _read_target(target: Path) -> bytes | None:
    try:
        with target.open("rb") as handle:
            return handle.read()
    except FileNotFoundError:
        return None


def _expected(rendered: Rendered, original: bytes | None) -> bytes:
    newline = "\r\n" if original is not None and b"\r\n" in original else "\n"
    generated = rendered.content.replace("\n", newline)
    if not rendered.managed_block:
        return generated.encode("utf-8")
    try:
        existing = original.decode("utf-8") if original is not None else ""
    except UnicodeDecodeError as exc:
        raise ConfigError([f"{rendered.path}: existing file is not UTF-8: {exc}"]) from None
    return _apply_block(existing, rendered.content, newline).encode("utf-8")


def _prepare(profile: Profile) -> list[Prepared]:
    """Read and generate every target before any filesystem mutation."""
    prepared: list[Prepared] = []
    seen: set[Path] = set()
    for rendered in render(profile):
        if rendered.path in seen:
            raise ConfigError([f"duplicate generated target: {rendered.path}"])
        seen.add(rendered.path)
        target = _safe_target(profile.root, rendered.path)
        original = _read_target(target)
        prepared.append(Prepared(rendered, target, original, _expected(rendered, original)))
    return prepared


def expected_content(root: Path, rendered: Rendered) -> str:
    """Compatibility helper used by callers that need one validated render."""
    target = _safe_target(root, rendered.path)
    return _expected(rendered, _read_target(target)).decode("utf-8")


def check(profile: Profile) -> list[Path]:
    """Return the paths whose checked-in content differs from the render."""
    return [item.rendered.path for item in _prepare(profile) if item.original != item.expected]


def _ensure_parent(root: Path, relative: Path) -> None:
    current = root.resolve(strict=True)
    for part in relative.parent.parts:
        current = current / part
        try:
            metadata = os.lstat(current)
        except FileNotFoundError:
            os.mkdir(current)
            metadata = os.lstat(current)
        if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISDIR(metadata.st_mode):
            raise ConfigError([f"generated target {relative}: unsafe parent {current}"])


def _stage(item: Prepared, root: Path) -> Path:
    _ensure_parent(root, item.rendered.path)
    descriptor, temporary = tempfile.mkstemp(prefix=f".{item.target.name}.", dir=item.target.parent)
    temporary_path = Path(temporary)
    try:
        if item.original is not None:
            os.fchmod(descriptor, os.lstat(item.target).st_mode & 0o777)
        else:
            os.fchmod(descriptor, 0o644)
        with os.fdopen(descriptor, "wb") as handle:
            descriptor = -1
            handle.write(item.expected)
            handle.flush()
            os.fsync(handle.fileno())
    except BaseException:
        if descriptor >= 0:
            os.close(descriptor)
        temporary_path.unlink(missing_ok=True)
        raise
    return temporary_path


def write(profile: Profile) -> list[Path]:
    """Write every rendered file; return the paths that changed."""
    prepared = _prepare(profile)
    changed = [item for item in prepared if item.original != item.expected]
    if not changed:
        return []

    staged: list[tuple[Prepared, Path]] = []
    try:
        for item in changed:
            staged.append((item, _stage(item, profile.root)))

        # Compare every render-time input again after staging and before the
        # replacement phase, so a conflict fails without changing any target.
        for item in prepared:
            target = _safe_target(profile.root, item.rendered.path)
            if _read_target(target) != item.original:
                raise ConfigError([f"{item.rendered.path}: changed concurrently; no files written"])

        for item, temporary in staged:
            os.replace(temporary, item.target)
        return [item.rendered.path for item in changed]
    finally:
        for _, temporary in staged:
            temporary.unlink(missing_ok=True)
