"""Render consumer wiring from ``workflow.toml``.

Generated content is checked in so it stays reviewable. Files a consumer
already owns (``AGENTS.md``, ``CLAUDE.md``) receive one managed block between
markers and are otherwise untouched. Files the package fully owns live under
``.loopzero/`` and ``.cursor/rules/``. ``check`` renders in memory and reports
drift without changing generated targets; it may create the sync lock metadata.
"""

from __future__ import annotations

import errno
import fcntl
import json
import os
import secrets
import stat
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator

from .config import ConfigError, Profile

BEGIN = "<!-- loopzero:begin generated by `loopzero sync`; do not edit inside -->"
END = "<!-- loopzero:end -->"
LOCK_PATH = Path(".loopzero/sync.lock")
PARTIAL_PATH = Path(".loopzero/generated.json.partial")
_DIRECTORY_FLAGS = os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC


@dataclass(frozen=True)
class Rendered:
    path: Path
    content: str
    managed_block: bool


@dataclass(frozen=True)
class Prepared:
    rendered: Rendered
    original: bytes | None
    original_mode: int | None
    expected: bytes


@dataclass(frozen=True)
class DirectoryHandle:
    relative: Path
    descriptor: int
    identity: tuple[int, int]


@dataclass(frozen=True)
class TargetState:
    content: bytes
    mode: int


def _pointer_block(profile: Profile, adapter: str) -> str:
    snapshot = profile.core_path.as_posix()
    return (
        f"{BEGIN}\n"
        f"Shared workflow: read `{snapshot}/adapters/{adapter}.md`, then "
        f"`{snapshot}/CONTRACT.md` and `workflow.toml`. Source revision "
        f"`{profile.core_revision}` from {profile.core_repository}. "
        f"Run `loopzero sync --check` before publishing wiring changes.\n"
        f"{END}\n"
    )


def _cursor_rule(profile: Profile) -> str:
    snapshot = profile.core_path.as_posix()
    return (
        "---\n"
        "description: loop-zero shared workflow entry point (generated)\n"
        "alwaysApply: true\n"
        "---\n\n"
        f"Read `{snapshot}/CONTRACT.md` and `workflow.toml` before workflow work. "
        f"Selected profiles: {', '.join(profile.profiles) or 'none'}. "
        f"Source revision `{profile.core_revision}`.\n"
        "One mutable task owns one worktree; acquire the writer lease before "
        "mutating; validation children have no commit authority.\n"
    )


def _claude_settings_fragment(profile: Profile) -> str:
    fragment = {
        "$comment": (
            "generated by `loopzero sync`; merge into .claude/settings.json. "
            "Hook execution is installed by the kernel, not this package skeleton"
        ),
        "hooks": {},
    }
    return json.dumps(fragment, indent=2, sort_keys=True) + "\n"


def _manifest(profile: Profile, files: list[Rendered]) -> str:
    manifest = {
        "core_revision": profile.core_revision,
        "epoch": profile.epoch,
        "generated": sorted(r.path.as_posix() for r in files),
    }
    return json.dumps(manifest, indent=2, sort_keys=True) + "\n"


def render(profile: Profile) -> list[Rendered]:
    files = [
        Rendered(Path("AGENTS.md"), _pointer_block(profile, "codex"), True),
        Rendered(Path("CLAUDE.md"), _pointer_block(profile, "claude"), True),
        Rendered(Path(".cursor/rules/loopzero.mdc"), _cursor_rule(profile), False),
        Rendered(Path(".loopzero/claude-settings-fragment.json"), _claude_settings_fragment(profile), False),
    ]
    files.append(Rendered(Path(".loopzero/generated.json"), _manifest(profile, files), False))
    return files


def _line_value(line: str) -> str:
    if line.endswith("\r\n"):
        return line[:-2]
    if line.endswith(("\r", "\n")):
        return line[:-1]
    return line


def _apply_block(existing: str, block: str, newline: str = "\n") -> str:
    lines = existing.splitlines(keepends=True)
    values = [_line_value(line) for line in lines]
    for value in values:
        if (BEGIN in value and value != BEGIN) or (END in value and value != END):
            raise ConfigError(["managed markers must be exact standalone lines"])
    begins = [index for index, value in enumerate(values) if value == BEGIN]
    ends = [index for index, value in enumerate(values) if value == END]
    if len(begins) != len(ends) or len(begins) not in (0, 1):
        raise ConfigError(["managed markers must contain zero or one matched pair"])
    if begins and begins[0] >= ends[0]:
        raise ConfigError(["managed markers are reversed or malformed"])

    block = block.replace("\n", newline)
    if begins:
        head = "".join(lines[: begins[0]])
        tail = "".join(lines[ends[0] + 1 :]).lstrip("\r\n")
        return head + block + (newline + tail if tail else "")
    if existing and not existing.endswith(("\r", "\n")):
        existing += newline
    return existing + (newline if existing else "") + block


def _validate_relative(relative: Path) -> None:
    if relative.is_absolute() or not relative.parts or ".." in relative.parts:
        raise ConfigError([f"generated target {relative}: must remain inside the repository"])


def _safe_target(root: Path, relative: Path) -> Path:
    """Validate a generated target for compatibility callers."""
    _validate_relative(relative)
    try:
        root = root.resolve(strict=True)
    except OSError as exc:
        raise ConfigError([f"repository root is unavailable: {exc}"]) from None
    target = root / relative
    try:
        target.resolve(strict=False).relative_to(root)
    except (OSError, ValueError):
        raise ConfigError([f"generated target {relative}: resolves outside the repository"]) from None

    current = root
    missing = False
    for index, part in enumerate(relative.parts):
        current = current / part
        if missing:
            continue
        try:
            metadata = os.lstat(current)
        except FileNotFoundError:
            missing = True
            continue
        except OSError as exc:
            raise ConfigError([f"generated target {relative}: cannot inspect {current}: {exc}"]) from None
        if stat.S_ISLNK(metadata.st_mode):
            raise ConfigError([f"generated target {relative}: symlink component {current} is forbidden"])
        final = index == len(relative.parts) - 1
        if final and not stat.S_ISREG(metadata.st_mode):
            raise ConfigError([f"generated target {relative}: existing target must be a regular file"])
        if not final and not stat.S_ISDIR(metadata.st_mode):
            raise ConfigError([f"generated target {relative}: parent {current} is not a directory"])
    return target


def _identity(metadata: os.stat_result) -> tuple[int, int]:
    return metadata.st_dev, metadata.st_ino


def _open_absolute_directory(path: Path) -> int:
    """Open an absolute directory by no-follow traversal from ``/``."""
    if not path.is_absolute():
        raise ConfigError([f"repository root {path}: must be absolute"])
    descriptor = os.open("/", _DIRECTORY_FLAGS)
    try:
        for part in path.parts[1:]:
            metadata = os.stat(part, dir_fd=descriptor, follow_symlinks=False)
            if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISDIR(metadata.st_mode):
                raise ConfigError([f"repository path component {part!r} is not a real directory"])
            child = os.open(part, _DIRECTORY_FLAGS, dir_fd=descriptor)
            if _identity(os.fstat(child)) != _identity(metadata):
                os.close(child)
                raise ConfigError([f"repository path component {part!r} changed concurrently"])
            os.close(descriptor)
            descriptor = child
        return descriptor
    except ConfigError:
        os.close(descriptor)
        raise
    except OSError as exc:
        os.close(descriptor)
        raise ConfigError([f"repository root is unavailable: {exc}"]) from None


def _verify_directory(handle: DirectoryHandle) -> None:
    try:
        metadata = os.fstat(handle.descriptor)
    except OSError as exc:
        raise ConfigError([f"generated parent {handle.relative}: cannot re-verify: {exc}"]) from None
    if not stat.S_ISDIR(metadata.st_mode) or _identity(metadata) != handle.identity:
        raise ConfigError([f"generated parent {handle.relative}: changed concurrently"])


def _open_parent(root_descriptor: int, relative: Path, *, create: bool) -> DirectoryHandle | None:
    """Open a target parent component-by-component relative to the root fd."""
    _validate_relative(relative)
    descriptor = os.dup(root_descriptor)
    parent = relative.parent
    try:
        for part in parent.parts:
            if part in ("", "."):
                continue
            try:
                metadata = os.stat(part, dir_fd=descriptor, follow_symlinks=False)
            except FileNotFoundError:
                if not create:
                    os.close(descriptor)
                    return None
                os.mkdir(part, 0o755, dir_fd=descriptor)
                os.fsync(descriptor)
                metadata = os.stat(part, dir_fd=descriptor, follow_symlinks=False)
            if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISDIR(metadata.st_mode):
                raise ConfigError(
                    [f"generated target {relative}: symlink or non-directory parent component {part}"]
                )
            child = os.open(part, _DIRECTORY_FLAGS, dir_fd=descriptor)
            if _identity(os.fstat(child)) != _identity(metadata):
                os.close(child)
                raise ConfigError([f"generated target {relative}: parent changed concurrently"])
            os.close(descriptor)
            descriptor = child
        metadata = os.fstat(descriptor)
        return DirectoryHandle(parent, descriptor, _identity(metadata))
    except ConfigError:
        os.close(descriptor)
        raise
    except OSError as exc:
        os.close(descriptor)
        raise ConfigError([f"generated target {relative}: cannot open parent: {exc}"]) from None


def _read_name(handle: DirectoryHandle, name: str, display: Path) -> TargetState | None:
    _verify_directory(handle)
    try:
        descriptor = os.open(name, os.O_RDONLY | os.O_NOFOLLOW | os.O_CLOEXEC, dir_fd=handle.descriptor)
    except FileNotFoundError:
        return None
    except OSError as exc:
        if exc.errno == errno.ELOOP:
            raise ConfigError([f"generated target {display}: symlink target is forbidden"]) from None
        raise ConfigError([f"generated target {display}: cannot open without following links: {exc}"]) from None
    try:
        metadata = os.fstat(descriptor)
        if not stat.S_ISREG(metadata.st_mode):
            raise ConfigError([f"generated target {display}: existing target must be a regular file"])
        chunks: list[bytes] = []
        while chunk := os.read(descriptor, 1024 * 1024):
            chunks.append(chunk)
        return TargetState(b"".join(chunks), stat.S_IMODE(metadata.st_mode))
    except OSError as exc:
        raise ConfigError([f"generated target {display}: cannot read: {exc}"]) from None
    finally:
        os.close(descriptor)


def _read_relative(root_descriptor: int, relative: Path) -> TargetState | None:
    handle = _open_parent(root_descriptor, relative, create=False)
    if handle is None:
        return None
    try:
        return _read_name(handle, relative.name, relative)
    finally:
        os.close(handle.descriptor)


def _expected(rendered: Rendered, original: bytes | None) -> bytes:
    newline = "\r\n" if original is not None and b"\r\n" in original else "\n"
    generated = rendered.content.replace("\n", newline)
    if not rendered.managed_block:
        return generated.encode("utf-8")
    try:
        existing = original.decode("utf-8") if original is not None else ""
    except UnicodeDecodeError as exc:
        raise ConfigError([f"{rendered.path}: existing file is not UTF-8: {exc}"]) from None
    return _apply_block(existing, rendered.content, newline).encode("utf-8")


def _prepare_from_fd(profile: Profile, root_descriptor: int) -> list[Prepared]:
    """Read and generate every target before any filesystem mutation."""
    prepared: list[Prepared] = []
    seen: set[Path] = set()
    for rendered in render(profile):
        if rendered.path in seen:
            raise ConfigError([f"duplicate generated target: {rendered.path}"])
        seen.add(rendered.path)
        _validate_relative(rendered.path)
        state = _read_relative(root_descriptor, rendered.path)
        original = state.content if state is not None else None
        mode = state.mode if state is not None else None
        prepared.append(
            Prepared(rendered, original, mode, _expected(rendered, original))
        )
    return prepared


def _prepare(profile: Profile) -> list[Prepared]:
    root_descriptor = _open_absolute_directory(profile.root)
    try:
        return _prepare_from_fd(profile, root_descriptor)
    finally:
        os.close(root_descriptor)


def expected_content(root: Path, rendered: Rendered) -> str:
    """Compatibility helper used by callers that need one validated render."""
    root = Path(root).resolve(strict=True)
    _safe_target(root, rendered.path)
    root_descriptor = _open_absolute_directory(root)
    try:
        state = _read_relative(root_descriptor, rendered.path)
    finally:
        os.close(root_descriptor)
    return _expected(rendered, state.content if state is not None else None).decode("utf-8")


@contextmanager
def _locked_root(root: Path) -> Iterator[int]:
    """Open the repository and hold its repository-wide sync lock exclusively."""
    root_descriptor = _open_absolute_directory(root)
    lock_parent = _open_parent(root_descriptor, LOCK_PATH, create=True)
    assert lock_parent is not None
    lock_descriptor = -1
    try:
        try:
            lock_descriptor = os.open(
                LOCK_PATH.name,
                os.O_RDWR | os.O_CREAT | os.O_NOFOLLOW | os.O_CLOEXEC,
                0o644,
                dir_fd=lock_parent.descriptor,
            )
            if not stat.S_ISREG(os.fstat(lock_descriptor).st_mode):
                raise ConfigError([f"sync lock {LOCK_PATH}: must be a regular file"])
            fcntl.flock(lock_descriptor, fcntl.LOCK_EX)
        except OSError as exc:
            raise ConfigError([f"sync lock {LOCK_PATH}: unavailable: {exc}"]) from None
        yield root_descriptor
    finally:
        if lock_descriptor >= 0:
            os.close(lock_descriptor)
        os.close(lock_parent.descriptor)
        os.close(root_descriptor)


def _partial_exists(root_descriptor: int) -> bool:
    state = _read_relative(root_descriptor, PARTIAL_PATH)
    return state is not None


def _partial_handle(root_descriptor: int) -> DirectoryHandle:
    handle = _open_parent(root_descriptor, PARTIAL_PATH, create=True)
    assert handle is not None
    return handle


def _write_partial(handle: DirectoryHandle, changed: list[Prepared]) -> None:
    _verify_directory(handle)
    payload = json.dumps(
        {"state": "replacement-in-progress", "targets": [str(item.rendered.path) for item in changed]},
        indent=2,
        sort_keys=True,
    ).encode("utf-8") + b"\n"
    temporary = f".{PARTIAL_PATH.name}.{secrets.token_hex(12)}"
    descriptor = -1
    try:
        descriptor = os.open(
            temporary,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW | os.O_CLOEXEC,
            0o600,
            dir_fd=handle.descriptor,
        )
        try:
            os.fchmod(descriptor, 0o644)
            offset = 0
            while offset < len(payload):
                offset += os.write(descriptor, payload[offset:])
            os.fsync(descriptor)
        finally:
            os.close(descriptor)
            descriptor = -1
        os.rename(
            temporary,
            PARTIAL_PATH.name,
            src_dir_fd=handle.descriptor,
            dst_dir_fd=handle.descriptor,
        )
        os.fsync(handle.descriptor)
    except OSError as exc:
        if descriptor >= 0:
            os.close(descriptor)
        try:
            os.unlink(temporary, dir_fd=handle.descriptor)
        except FileNotFoundError:
            pass
        raise ConfigError([f"interrupted-sync marker {PARTIAL_PATH}: cannot write: {exc}"]) from None


def _remove_partial(handle: DirectoryHandle) -> None:
    _verify_directory(handle)
    try:
        os.unlink(PARTIAL_PATH.name, dir_fd=handle.descriptor)
        os.fsync(handle.descriptor)
    except FileNotFoundError:
        pass
    except OSError as exc:
        raise ConfigError([f"interrupted-sync marker {PARTIAL_PATH}: cannot remove: {exc}"]) from None


def check(profile: Profile) -> list[Path]:
    """Return the paths whose checked-in content differs from the render."""
    with _locked_root(profile.root) as root_descriptor:
        if _partial_exists(root_descriptor):
            raise ConfigError(
                [f"interrupted sync: {PARTIAL_PATH} exists; run `loopzero sync` to recover"]
            )
        prepared = _prepare_from_fd(profile, root_descriptor)
        return [item.rendered.path for item in prepared if item.original != item.expected]


def _stage(item: Prepared, parent: DirectoryHandle) -> str:
    _verify_directory(parent)
    temporary = f".{item.rendered.path.name}.{secrets.token_hex(12)}"
    descriptor = -1
    try:
        descriptor = os.open(
            temporary,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW | os.O_CLOEXEC,
            0o600,
            dir_fd=parent.descriptor,
        )
        os.fchmod(descriptor, item.original_mode if item.original_mode is not None else 0o644)
        offset = 0
        while offset < len(item.expected):
            offset += os.write(descriptor, item.expected[offset:])
        os.fsync(descriptor)
    except BaseException:
        if descriptor >= 0:
            os.close(descriptor)
        try:
            os.unlink(temporary, dir_fd=parent.descriptor)
        except FileNotFoundError:
            pass
        raise
    else:
        os.close(descriptor)
    return temporary


def _verify_reachable(root_descriptor: int, handle: DirectoryHandle) -> None:
    probe = _open_parent(root_descriptor, handle.relative / "probe", create=False)
    if probe is None:
        raise ConfigError([f"generated parent {handle.relative}: disappeared concurrently"])
    try:
        if probe.identity != handle.identity:
            raise ConfigError([f"generated parent {handle.relative}: changed concurrently"])
    finally:
        os.close(probe.descriptor)


def _verify_root_path(root: Path, root_descriptor: int) -> None:
    probe = _open_absolute_directory(root)
    try:
        if _identity(os.fstat(probe)) != _identity(os.fstat(root_descriptor)):
            raise ConfigError(["repository root changed concurrently"])
    finally:
        os.close(probe)


def write(profile: Profile) -> list[Path]:
    """Write every rendered file; return the paths that changed."""
    with _locked_root(profile.root) as root_descriptor:
        had_partial = _partial_exists(root_descriptor)
        prepared = _prepare_from_fd(profile, root_descriptor)
        changed = [item for item in prepared if item.original != item.expected]
        partial_parent = _partial_handle(root_descriptor)
        if not changed:
            try:
                if had_partial:
                    _remove_partial(partial_parent)
                return []
            finally:
                os.close(partial_parent.descriptor)

        parents: dict[Path, DirectoryHandle] = {partial_parent.relative: partial_parent}
        staged: list[tuple[Prepared, DirectoryHandle, str]] = []
        try:
            for item in prepared:
                relative_parent = item.rendered.path.parent
                if relative_parent not in parents:
                    handle = _open_parent(root_descriptor, item.rendered.path, create=True)
                    assert handle is not None
                    parents[relative_parent] = handle
            for item in changed:
                parent = parents[item.rendered.path.parent]
                staged.append((item, parent, _stage(item, parent)))

            # Re-read every render-time input through the anchored directory
            # descriptors. Honest concurrent syncs cannot enter this section
            # because they hold the same flock.
            _verify_root_path(profile.root, root_descriptor)
            for parent in parents.values():
                _verify_reachable(root_descriptor, parent)
            for item in prepared:
                state = _read_name(
                    parents[item.rendered.path.parent], item.rendered.path.name, item.rendered.path
                )
                current = state.content if state is not None else None
                current_mode = state.mode if state is not None else None
                if current != item.original or current_mode != item.original_mode:
                    raise ConfigError(
                        [f"{item.rendered.path}: changed concurrently; no files written"]
                    )

            _write_partial(partial_parent, changed)
            for index, (item, parent, temporary) in enumerate(staged):
                _verify_directory(parent)
                try:
                    os.rename(
                        temporary,
                        item.rendered.path.name,
                        src_dir_fd=parent.descriptor,
                        dst_dir_fd=parent.descriptor,
                    )
                except OSError as exc:
                    raise ConfigError(
                        [
                            f"{item.rendered.path}: replacement failed; "
                            f"interrupted-sync marker retained: {exc}"
                        ]
                    ) from None
                os.fsync(parent.descriptor)
                staged[index] = (item, parent, "")
            _remove_partial(partial_parent)
            return [item.rendered.path for item in changed]
        finally:
            for _, parent, temporary in staged:
                if temporary:
                    try:
                        os.unlink(temporary, dir_fd=parent.descriptor)
                    except FileNotFoundError:
                        pass
            for parent in parents.values():
                os.close(parent.descriptor)
