"""Render consumer wiring from ``workflow.toml``.

Generated content is checked in so it stays reviewable. Files a consumer
already owns (``AGENTS.md``, ``CLAUDE.md``) receive one managed block between
markers and are otherwise untouched. Files the package fully owns live under
``.loopzero/`` and ``.cursor/rules/``. ``check`` renders in memory and reports
drift without changing generated targets; it may create the sync lock metadata.
"""

from __future__ import annotations

import fcntl
import hashlib
import json
import os
import re
import secrets
import stat
from contextlib import contextmanager
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator

from .config import (
    MANAGED_BLOCK_BEGIN,
    MANAGED_BLOCK_END,
    MANAGED_MARKER_TOKENS,
    ConfigError,
    Profile,
)

BEGIN = MANAGED_BLOCK_BEGIN
END = MANAGED_BLOCK_END
LOCK_PATH = Path(".loopzero/sync.lock")
PARTIAL_PATH = Path(".loopzero/generated.json.partial")
SKILLS_MANIFEST_PATH = Path(".loopzero/skills-manifest.json")
SKILL_OVERLAY_BEGIN = "<!-- loopzero:skill-overlay:begin generated by `loopzero sync`; do not edit -->"
SKILL_OVERLAY_END = "<!-- loopzero:skill-overlay:end -->"
_DIRECTORY_FLAGS = os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW | os.O_CLOEXEC
_SKILL_TOKEN = re.compile(r"\{\{(?P<name>[a-z0-9_.]+)\}\}")

_COMMAND_DEFAULTS = {
    "audit_graph": "make audit-graph",
    "audit_graph_backend": "make audit-graph-be",
    "audit_graph_frontend": "make audit-graph-fe",
    "audit_python_coverage": "make audit-python-coverage",
    "audit_python_dead_code": "make audit-python-dead-code",
    "backlog": "make backlog",
    "backlog_delegation": "make backlog-delegation",
    "check_skills": "make check-skill-*",
    "ci_mirror_check": "make ci-mirror-check",
    "claims_check": "make claims-check",
    "db_test_start": "make db-test-start",
    "delivery_status": "make delivery-status",
    "docs_archive_candidates": "make docs-archive-candidates",
    "docs_audit": "make docs-audit",
    "docs_verify": "make docs-verify",
    "gates_verify": "make gates-verify",
    "health": "make health",
    "health_backend": "make health TARGET=python",
    "health_frontend": "make health TARGET=next",
    "infra_start": "make infra-start",
    "learnings_status": "make learnings-status",
    "metabolism_status": "make metabolism-status",
    "meters_snapshot": "make meters-snapshot",
    "openapi_export": "make openapi-export",
    "openapi_generate": "make openapi-generate",
    "orient": "make orient",
    "phase_stats": "make phase-stats",
    "product_pulse": "make product-pulse DAYS=30",
    "reentry": "make reentry",
    "reentry_coverage": "make reentry-coverage DAYS=14",
    "reflection_digest": "make reflection-digest DAYS=14",
    "skill_stats": "make skill-stats DAYS=14",
    "test_agent_tooling": "make test-agent-tooling",
    "test_backend": "make test-be",
    "test_backend_precommit": "make test-be-precommit-unit",
    "test_backend_slow": "make test-be-slow",
    "test_backend_unit": "make test-be-unit",
    "weekly_issue": "make weekly-issue",
    "worktree_claims": "make worktree-claims",
    "worktree_setup": "make worktree-setup",
}


@dataclass(frozen=True)
class Rendered:
    path: Path
    content: str
    managed_block: bool
    symlink: bool = False


@dataclass(frozen=True)
class Prepared:
    rendered: Rendered
    original: bytes | None
    original_mode: int | None
    expected: bytes
    original_symlink: bool = False


@dataclass(frozen=True)
class DirectoryHandle:
    relative: Path
    descriptor: int
    identity: tuple[int, int]


@dataclass(frozen=True)
class TargetState:
    content: bytes
    mode: int | None
    symlink: bool = False


def _pointer_block(profile: Profile, adapter: str) -> str:
    snapshot = profile.core_path.as_posix()
    return (
        f"{BEGIN}\n"
        f"Shared workflow: read `{snapshot}/adapters/{adapter}.md`, then "
        f"`{snapshot}/CONTRACT.md` and `workflow.toml`. Source revision "
        f"`{profile.core_revision}` from {profile.core_repository}. "
        f"Run `loopzero sync --check` before publishing wiring changes.\n"
        f"{END}\n"
    )


def _cursor_rule(profile: Profile) -> str:
    snapshot = profile.core_path.as_posix()
    return (
        "---\n"
        "description: loop-zero shared workflow entry point (generated)\n"
        "alwaysApply: true\n"
        "---\n\n"
        f"Read `{snapshot}/CONTRACT.md` and `workflow.toml` before workflow work. "
        f"Selected profiles: {', '.join(profile.profiles) or 'none'}. "
        f"Source revision `{profile.core_revision}`.\n"
        "One mutable task owns one worktree; acquire the writer lease before "
        "mutating; validation children have no commit authority.\n"
    )


def _claude_settings_fragment(profile: Profile) -> str:
    fragment = {
        "$comment": (
            "generated by `loopzero sync`; merge into .claude/settings.json. "
            "Hook execution is installed by the kernel, not this package skeleton"
        ),
        "hooks": {},
    }
    return json.dumps(fragment, indent=2, sort_keys=True) + "\n"


def _manifest(profile: Profile, files: list[Rendered]) -> str:
    manifest = {
        "core_revision": profile.core_revision,
        "epoch": profile.epoch,
        "generated": sorted(r.path.as_posix() for r in files),
    }
    return json.dumps(manifest, indent=2, sort_keys=True) + "\n"


def _relative_from_skill(profile: Profile, destination: Path) -> str:
    return os.path.relpath(destination, profile.skills_dir / "skill-name")


def _skill_values(profile: Profile) -> dict[str, str]:
    package = profile.raw.get("package", {})
    toolchain = profile.toolchain
    commands = toolchain.get("commands", {})
    if not isinstance(commands, dict):
        commands = {}
    docs = Path("docs")
    rules = profile.skills_dir.parent / "rules"
    values = {
        "package.product_name": str(package.get("product_name", "IntelFlo")),
        "package.env_prefix": profile.env_prefix,
        "package.primary_env": str(package.get("primary_env", f"{profile.env_prefix}_PRIMARY")),
        "package.audit_root": profile.audit_root.as_posix(),
        "package.docs_root": str(package.get("docs_root", _relative_from_skill(profile, docs))),
        "package.rules_root": str(package.get("rules_root", _relative_from_skill(profile, rules))),
        "package.constraints_file": str(
            package.get("constraints_file", _relative_from_skill(profile, Path("AGENTS.md")))
        ),
        "package.delivery_guide": str(
            package.get(
                "delivery_guide",
                _relative_from_skill(
                    profile, docs / "guides/dev-workflow/loop-zero-delivery.md"
                ),
            )
        ),
        "package.skills_readme": str(package.get("skills_readme", "../README.md")),
        "package.docs_dir": str(package.get("docs_dir", "docs")),
        "package.weekly_issue_workflow": str(
            package.get("weekly_issue_workflow", ".github/workflows/weekly-issue.yml")
        ),
        "package.openapi_document": str(
            package.get("openapi_document", "shared-data/openapi.json")
        ),
        "package.commit_identity": str(
            package.get("commit_identity", "Vercel-authorized eowca")
        ),
        "package.frontend_full_env": str(
            package.get("frontend_full_env", "CI_MIRROR_FULL_FRONTEND")
        ),
        "package.suppressions_file": str(
            package.get("suppressions_file", _relative_from_skill(profile, Path("suppressions.yaml")))
        ),
        "package.core_contract": str(
            package.get(
                "core_contract",
                _relative_from_skill(profile, profile.core_path / "CONTRACT.md"),
            )
        ),
        "package.core_handoff": str(
            package.get(
                "core_handoff",
                _relative_from_skill(profile, profile.core_path / "HANDOFF.md"),
            )
        ),
        "toolchain.backend_dir": str(toolchain.get("backend_dir", "fastapi_backend")),
        "toolchain.frontend_dir": str(toolchain.get("frontend_dir", "nextjs-frontend")),
        "toolchain.scripts_dir": str(toolchain.get("scripts_dir", "scripts")),
        "toolchain.scripts_root": str(
            toolchain.get("scripts_root", _relative_from_skill(profile, Path("scripts")))
        ),
        "toolchain.python": str(toolchain.get("python", "python3")),
        "toolchain.system_python": str(toolchain.get("system_python", "/usr/bin/python3")),
        "toolchain.uv": str(toolchain.get("uv", "uv")),
        "toolchain.pnpm": str(toolchain.get("pnpm", "pnpm")),
        "toolchain.pytest": str(toolchain.get("pytest", "pytest")),
        "toolchain.vitest": str(toolchain.get("vitest", "vitest")),
    }
    values.update(
        {
            f"toolchain.commands.{name}": str(commands.get(name, default))
            for name, default in _COMMAND_DEFAULTS.items()
        }
    )
    return values


def _substitute_skill(text: str, profile: Profile, source: Path) -> str:
    values = _skill_values(profile)

    def replace(match: re.Match[str]) -> str:
        name = match.group("name")
        if name not in values:
            raise ConfigError([f"{source}: unknown skill template token {name!r}"])
        return values[name]

    rendered = _SKILL_TOKEN.sub(replace, text)
    unresolved = _SKILL_TOKEN.search(rendered)
    if unresolved:
        raise ConfigError([f"{source}: unresolved skill template token {unresolved.group('name')!r}"])
    return rendered


def _read_skill_source(path: Path) -> str:
    try:
        metadata = os.lstat(path)
        if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISREG(metadata.st_mode):
            raise ConfigError([f"skill source {path}: must be a regular file"])
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        raise ConfigError([f"skill source {path}: missing"]) from None
    except (OSError, UnicodeError) as exc:
        raise ConfigError([f"skill source {path}: cannot read: {exc}"]) from None


def _skill_files(
    profile: Profile, shadowed: set[str]
) -> tuple[list[Rendered], dict[str, dict[str, object]]]:
    source_root = profile.snapshot_dir / "skills"
    if not source_root.is_dir() or source_root.is_symlink():
        raise ConfigError([f"skill source {source_root}: must be a real directory"])
    rendered: list[Rendered] = []
    records: dict[str, dict[str, object]] = {}

    def add_skill(name: str, directory: Path, *, vendor: bool) -> None:
        if name in shadowed:
            return
        files: list[str] = []
        digests: dict[str, str] = {}
        for source in sorted(directory.rglob("*"), key=lambda item: item.as_posix()):
            relative_source = source.relative_to(directory)
            if source.is_symlink():
                raise ConfigError([f"skill source {source}: symlinks are forbidden"])
            if source.name in {"PIN", "OVERLAY.md"} or source.is_dir():
                continue
            if not source.is_file():
                raise ConfigError([f"skill source {source}: must be a regular file"])
            content = _read_skill_source(source)
            if vendor and source.name == "SKILL.md":
                overlay_path = directory / "OVERLAY.md"
                overlay = _read_skill_source(overlay_path)
                content = (
                    content
                    + ("" if content.endswith("\n") else "\n")
                    + "\n"
                    + SKILL_OVERLAY_BEGIN
                    + "\n"
                    + overlay
                    + ("" if overlay.endswith("\n") else "\n")
                    + SKILL_OVERLAY_END
                    + "\n"
                )
            elif not vendor and source.suffix == ".md":
                content = _substitute_skill(content, profile, source)
            target = profile.skills_dir / name / relative_source
            rendered.append(Rendered(target, content, False))
            relative_name = relative_source.as_posix()
            files.append(relative_name)
            digests[relative_name] = hashlib.sha256(content.encode("utf-8")).hexdigest()
        if "SKILL.md" not in files:
            raise ConfigError([f"skill source {directory}: missing SKILL.md"])
        records[name] = {
            "source": "vendor" if vendor else "governance",
            "files": files,
            "sha256": digests,
        }

    for directory in sorted(source_root.iterdir(), key=lambda item: item.name):
        if directory.name == "vendor":
            continue
        if directory.is_symlink():
            raise ConfigError([f"skill source {directory}: symlinks are forbidden"])
        if not directory.is_dir():
            continue
        if (directory / "SKILL.md").is_file():
            add_skill(directory.name, directory, vendor=False)

    vendor_root = source_root / "vendor"
    if vendor_root.is_dir() and not vendor_root.is_symlink():
        for directory in sorted(vendor_root.iterdir(), key=lambda item: item.name):
            if directory.is_symlink():
                raise ConfigError([f"skill source {directory}: symlinks are forbidden"])
            if not directory.is_dir():
                continue
            if (directory / "SKILL.md").is_file():
                if directory.name in records:
                    raise ConfigError([f"duplicate rendered skill name: {directory.name}"])
                add_skill(directory.name, directory, vendor=True)
    return rendered, records


def _skills_manifest(
    profile: Profile,
    records: dict[str, dict[str, object]],
    shadowed: set[str],
    all_names: set[str],
) -> str:
    payload = {
        "core_revision": profile.core_revision,
        "skills_dir": profile.skills_dir.as_posix(),
        "skill_mirrors": [path.as_posix() for path in profile.skill_mirrors],
        "skills": records,
        "shadowed_consumer_skills": sorted(shadowed),
        "mirrored_skills": sorted(all_names),
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def render(
    profile: Profile,
    *,
    shadowed_skills: set[str] | None = None,
    consumer_skills: set[str] | None = None,
) -> list[Rendered]:
    shadowed = set(shadowed_skills or ())
    consumer = set(consumer_skills or ())
    files = [
        Rendered(Path("AGENTS.md"), _pointer_block(profile, "codex"), True),
        Rendered(Path("CLAUDE.md"), _pointer_block(profile, "claude"), True),
        Rendered(Path(".cursor/rules/loopzero.mdc"), _cursor_rule(profile), False),
        Rendered(Path(".loopzero/claude-settings-fragment.json"), _claude_settings_fragment(profile), False),
    ]
    skill_files, records = _skill_files(profile, shadowed)
    files.extend(skill_files)
    all_names = set(records) | consumer
    files.append(
        Rendered(
            SKILLS_MANIFEST_PATH,
            _skills_manifest(profile, records, shadowed, all_names),
            False,
        )
    )
    for mirror in profile.skill_mirrors:
        for name in sorted(all_names):
            target = os.path.relpath(profile.skills_dir / name, mirror)
            files.append(Rendered(mirror / name, target, False, symlink=True))
    files.append(Rendered(Path(".loopzero/generated.json"), _manifest(profile, files), False))
    for rendered in files:
        if rendered.symlink:
            continue
        marker_lines = [
            line
            for line in rendered.content.splitlines()
            if any(marker in line for marker in MANAGED_MARKER_TOKENS)
        ]
        expected = [BEGIN, END] if rendered.managed_block else []
        assert marker_lines == expected, f"unexpected managed marker in {rendered.path}"
    return files


def _line_value(line: str) -> str:
    if line.endswith("\r\n"):
        return line[:-2]
    if line.endswith(("\r", "\n")):
        return line[:-1]
    return line


def _apply_block(existing: str, block: str, newline: str = "\n") -> str:
    lines = existing.splitlines(keepends=True)
    values = [_line_value(line) for line in lines]
    for value in values:
        if (BEGIN in value and value != BEGIN) or (END in value and value != END):
            raise ConfigError(["managed markers must be exact standalone lines"])
    begins = [index for index, value in enumerate(values) if value == BEGIN]
    ends = [index for index, value in enumerate(values) if value == END]
    if len(begins) != len(ends) or len(begins) not in (0, 1):
        raise ConfigError(["managed markers must contain zero or one matched pair"])
    if begins and begins[0] >= ends[0]:
        raise ConfigError(["managed markers are reversed or malformed"])

    block = block.replace("\n", newline)
    if begins:
        head = "".join(lines[: begins[0]])
        tail = "".join(lines[ends[0] + 1 :]).lstrip("\r\n")
        return head + block + (newline + tail if tail else "")
    if existing and not existing.endswith(("\r", "\n")):
        existing += newline
    return existing + (newline if existing else "") + block


def _validate_relative(relative: Path) -> None:
    if relative.is_absolute() or not relative.parts or ".." in relative.parts:
        raise ConfigError([f"generated target {relative}: must remain inside the repository"])


def _safe_target(root: Path, relative: Path) -> Path:
    """Validate a generated target for compatibility callers."""
    _validate_relative(relative)
    try:
        root = root.resolve(strict=True)
    except OSError as exc:
        raise ConfigError([f"repository root is unavailable: {exc}"]) from None
    target = root / relative
    try:
        target.resolve(strict=False).relative_to(root)
    except (OSError, ValueError):
        raise ConfigError([f"generated target {relative}: resolves outside the repository"]) from None

    current = root
    missing = False
    for index, part in enumerate(relative.parts):
        current = current / part
        if missing:
            continue
        try:
            metadata = os.lstat(current)
        except FileNotFoundError:
            missing = True
            continue
        except OSError as exc:
            raise ConfigError([f"generated target {relative}: cannot inspect {current}: {exc}"]) from None
        if stat.S_ISLNK(metadata.st_mode):
            raise ConfigError([f"generated target {relative}: symlink component {current} is forbidden"])
        final = index == len(relative.parts) - 1
        if final and not stat.S_ISREG(metadata.st_mode):
            raise ConfigError([f"generated target {relative}: existing target must be a regular file"])
        if not final and not stat.S_ISDIR(metadata.st_mode):
            raise ConfigError([f"generated target {relative}: parent {current} is not a directory"])
    return target


def _identity(metadata: os.stat_result) -> tuple[int, int]:
    return metadata.st_dev, metadata.st_ino


def _open_absolute_directory(path: Path) -> int:
    """Open an absolute directory by no-follow traversal from ``/``."""
    if not path.is_absolute():
        raise ConfigError([f"repository root {path}: must be absolute"])
    descriptor = os.open("/", _DIRECTORY_FLAGS)
    try:
        for part in path.parts[1:]:
            metadata = os.stat(part, dir_fd=descriptor, follow_symlinks=False)
            if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISDIR(metadata.st_mode):
                raise ConfigError([f"repository path component {part!r} is not a real directory"])
            child = os.open(part, _DIRECTORY_FLAGS, dir_fd=descriptor)
            if _identity(os.fstat(child)) != _identity(metadata):
                os.close(child)
                raise ConfigError([f"repository path component {part!r} changed concurrently"])
            os.close(descriptor)
            descriptor = child
        return descriptor
    except ConfigError:
        os.close(descriptor)
        raise
    except OSError as exc:
        os.close(descriptor)
        raise ConfigError([f"repository root is unavailable: {exc}"]) from None


def _verify_directory(handle: DirectoryHandle) -> None:
    try:
        metadata = os.fstat(handle.descriptor)
    except OSError as exc:
        raise ConfigError([f"generated parent {handle.relative}: cannot re-verify: {exc}"]) from None
    if not stat.S_ISDIR(metadata.st_mode) or _identity(metadata) != handle.identity:
        raise ConfigError([f"generated parent {handle.relative}: changed concurrently"])


def _open_parent(root_descriptor: int, relative: Path, *, create: bool) -> DirectoryHandle | None:
    """Open a target parent component-by-component relative to the root fd."""
    _validate_relative(relative)
    descriptor = os.dup(root_descriptor)
    parent = relative.parent
    try:
        for part in parent.parts:
            if part in ("", "."):
                continue
            try:
                metadata = os.stat(part, dir_fd=descriptor, follow_symlinks=False)
            except FileNotFoundError:
                if not create:
                    os.close(descriptor)
                    return None
                os.mkdir(part, 0o755, dir_fd=descriptor)
                os.fsync(descriptor)
                metadata = os.stat(part, dir_fd=descriptor, follow_symlinks=False)
            if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISDIR(metadata.st_mode):
                raise ConfigError(
                    [f"generated target {relative}: symlink or non-directory parent component {part}"]
                )
            child = os.open(part, _DIRECTORY_FLAGS, dir_fd=descriptor)
            if _identity(os.fstat(child)) != _identity(metadata):
                os.close(child)
                raise ConfigError([f"generated target {relative}: parent changed concurrently"])
            os.close(descriptor)
            descriptor = child
        metadata = os.fstat(descriptor)
        return DirectoryHandle(parent, descriptor, _identity(metadata))
    except ConfigError:
        os.close(descriptor)
        raise
    except OSError as exc:
        os.close(descriptor)
        raise ConfigError([f"generated target {relative}: cannot open parent: {exc}"]) from None


def _read_name(
    handle: DirectoryHandle, name: str, display: Path, *, allow_symlink: bool = False
) -> TargetState | None:
    _verify_directory(handle)
    try:
        metadata = os.stat(name, dir_fd=handle.descriptor, follow_symlinks=False)
    except FileNotFoundError:
        return None
    except OSError as exc:
        raise ConfigError([f"generated target {display}: cannot inspect: {exc}"]) from None
    if stat.S_ISLNK(metadata.st_mode):
        if not allow_symlink:
            raise ConfigError([f"generated target {display}: symlink target is forbidden"])
        try:
            target = os.readlink(name, dir_fd=handle.descriptor)
        except OSError as exc:
            raise ConfigError([f"generated target {display}: cannot read symlink: {exc}"]) from None
        return TargetState(os.fsencode(target), None, True)
    if not stat.S_ISREG(metadata.st_mode):
        raise ConfigError([f"generated target {display}: existing target must be a regular file"])
    try:
        descriptor = os.open(
            name,
            os.O_RDONLY | os.O_NONBLOCK | os.O_NOFOLLOW | os.O_CLOEXEC,
            dir_fd=handle.descriptor,
        )
    except OSError as exc:
        raise ConfigError([f"generated target {display}: cannot open without following links: {exc}"]) from None
    try:
        opened = os.fstat(descriptor)
        if not stat.S_ISREG(opened.st_mode) or _identity(opened) != _identity(metadata):
            raise ConfigError([f"generated target {display}: existing target must be a regular file"])
        flags = fcntl.fcntl(descriptor, fcntl.F_GETFL)
        fcntl.fcntl(descriptor, fcntl.F_SETFL, flags & ~os.O_NONBLOCK)
        chunks: list[bytes] = []
        while chunk := os.read(descriptor, 1024 * 1024):
            chunks.append(chunk)
        return TargetState(b"".join(chunks), stat.S_IMODE(opened.st_mode))
    except OSError as exc:
        raise ConfigError([f"generated target {display}: cannot read: {exc}"]) from None
    finally:
        os.close(descriptor)


def _read_relative(
    root_descriptor: int, relative: Path, *, allow_symlink: bool = False
) -> TargetState | None:
    handle = _open_parent(root_descriptor, relative, create=False)
    if handle is None:
        return None
    try:
        return _read_name(handle, relative.name, relative, allow_symlink=allow_symlink)
    finally:
        os.close(handle.descriptor)


def _expected(rendered: Rendered, original: bytes | None) -> bytes:
    if rendered.symlink:
        return os.fsencode(rendered.content)
    newline = "\r\n" if original is not None and b"\r\n" in original else "\n"
    generated = rendered.content.replace("\n", newline)
    if not rendered.managed_block:
        return generated.encode("utf-8")
    try:
        existing = original.decode("utf-8") if original is not None else ""
    except UnicodeDecodeError as exc:
        raise ConfigError([f"{rendered.path}: existing file is not UTF-8: {exc}"]) from None
    return _apply_block(existing, rendered.content, newline).encode("utf-8")


def _read_skills_manifest(root_descriptor: int) -> set[str]:
    state = _read_relative(root_descriptor, SKILLS_MANIFEST_PATH)
    if state is None:
        return set()
    try:
        payload = json.loads(state.content.decode("utf-8"))
        skills = payload["skills"]
        if not isinstance(skills, dict) or any(not isinstance(name, str) for name in skills):
            raise ValueError("skills must be an object")
        return set(skills)
    except (KeyError, TypeError, ValueError, UnicodeError) as exc:
        raise ConfigError([f"{SKILLS_MANIFEST_PATH}: invalid rendered manifest: {exc}"]) from None


def _existing_skill_names(profile: Profile, root_descriptor: int) -> set[str]:
    probe = profile.skills_dir / ".loopzero-probe"
    handle = _open_parent(root_descriptor, probe, create=False)
    if handle is None:
        return set()
    try:
        names: set[str] = set()
        for name in os.listdir(handle.descriptor):
            metadata = os.stat(name, dir_fd=handle.descriptor, follow_symlinks=False)
            if stat.S_ISLNK(metadata.st_mode):
                raise ConfigError(
                    [f"canonical skill {profile.skills_dir / name}: symlink directories are forbidden"]
                )
            if stat.S_ISDIR(metadata.st_mode):
                names.add(name)
        return names
    except OSError as exc:
        raise ConfigError([f"canonical skills directory {profile.skills_dir}: cannot inspect: {exc}"]) from None
    finally:
        os.close(handle.descriptor)


def _prepare_from_fd(profile: Profile, root_descriptor: int) -> list[Prepared]:
    """Read and generate every target before any filesystem mutation."""
    prepared: list[Prepared] = []
    seen: set[Path] = set()
    existing_skills = _existing_skill_names(profile, root_descriptor)
    previously_managed = _read_skills_manifest(root_descriptor)
    shadowed = existing_skills - previously_managed
    rendered_files = (
        render(profile)
        if not shadowed and not existing_skills
        else render(
            profile,
            shadowed_skills=shadowed,
            consumer_skills=existing_skills,
        )
    )
    for rendered in rendered_files:
        if rendered.path in seen:
            raise ConfigError([f"duplicate generated target: {rendered.path}"])
        seen.add(rendered.path)
        _validate_relative(rendered.path)
        state = _read_relative(
            root_descriptor, rendered.path, allow_symlink=rendered.symlink
        )
        original = state.content if state is not None else None
        mode = state.mode if state is not None else None
        prepared.append(
            Prepared(
                rendered,
                original,
                mode,
                _expected(rendered, original),
                state.symlink if state is not None else False,
            )
        )
    return prepared


def _prepare(profile: Profile) -> list[Prepared]:
    root_descriptor = _open_absolute_directory(profile.root)
    try:
        return _prepare_from_fd(profile, root_descriptor)
    finally:
        os.close(root_descriptor)


def expected_content(root: Path, rendered: Rendered) -> str:
    """Compatibility helper used by callers that need one validated render."""
    root = Path(root).resolve(strict=True)
    _safe_target(root, rendered.path)
    root_descriptor = _open_absolute_directory(root)
    try:
        state = _read_relative(root_descriptor, rendered.path, allow_symlink=rendered.symlink)
    finally:
        os.close(root_descriptor)
    return _expected(rendered, state.content if state is not None else None).decode("utf-8")


@contextmanager
def _locked_root(root: Path) -> Iterator[int]:
    """Open the repository and hold its repository-wide sync lock exclusively."""
    root_descriptor = _open_absolute_directory(root)
    lock_parent = _open_parent(root_descriptor, LOCK_PATH, create=True)
    assert lock_parent is not None
    lock_descriptor = -1
    try:
        try:
            lock_descriptor = os.open(
                LOCK_PATH.name,
                os.O_RDWR | os.O_CREAT | os.O_NOFOLLOW | os.O_CLOEXEC,
                0o644,
                dir_fd=lock_parent.descriptor,
            )
            if not stat.S_ISREG(os.fstat(lock_descriptor).st_mode):
                raise ConfigError([f"sync lock {LOCK_PATH}: must be a regular file"])
            fcntl.flock(lock_descriptor, fcntl.LOCK_EX)
        except OSError as exc:
            raise ConfigError([f"sync lock {LOCK_PATH}: unavailable: {exc}"]) from None
        yield root_descriptor
    finally:
        if lock_descriptor >= 0:
            os.close(lock_descriptor)
        os.close(lock_parent.descriptor)
        os.close(root_descriptor)


def _partial_exists(root_descriptor: int) -> bool:
    state = _read_relative(root_descriptor, PARTIAL_PATH)
    return state is not None


def _partial_handle(root_descriptor: int) -> DirectoryHandle:
    handle = _open_parent(root_descriptor, PARTIAL_PATH, create=True)
    assert handle is not None
    return handle


def _write_partial(
    handle: DirectoryHandle, changed: list[Prepared], stale_links: dict[Path, str] | None = None
) -> None:
    _verify_directory(handle)
    payload = json.dumps(
        {
            "state": "replacement-in-progress",
            "targets": [str(item.rendered.path) for item in changed]
            + [str(path) for path in sorted(stale_links or {})],
        },
        indent=2,
        sort_keys=True,
    ).encode("utf-8") + b"\n"
    temporary = f".{PARTIAL_PATH.name}.{secrets.token_hex(12)}"
    descriptor = -1
    try:
        descriptor = os.open(
            temporary,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW | os.O_CLOEXEC,
            0o600,
            dir_fd=handle.descriptor,
        )
        try:
            os.fchmod(descriptor, 0o644)
            offset = 0
            while offset < len(payload):
                offset += os.write(descriptor, payload[offset:])
            os.fsync(descriptor)
        finally:
            os.close(descriptor)
            descriptor = -1
        os.rename(
            temporary,
            PARTIAL_PATH.name,
            src_dir_fd=handle.descriptor,
            dst_dir_fd=handle.descriptor,
        )
        os.fsync(handle.descriptor)
    except OSError as exc:
        if descriptor >= 0:
            os.close(descriptor)
        try:
            os.unlink(temporary, dir_fd=handle.descriptor)
        except FileNotFoundError:
            pass
        raise ConfigError([f"interrupted-sync marker {PARTIAL_PATH}: cannot write: {exc}"]) from None


def _remove_partial(handle: DirectoryHandle) -> None:
    _verify_directory(handle)
    try:
        os.unlink(PARTIAL_PATH.name, dir_fd=handle.descriptor)
        os.fsync(handle.descriptor)
    except FileNotFoundError:
        pass
    except OSError as exc:
        raise ConfigError([f"interrupted-sync marker {PARTIAL_PATH}: cannot remove: {exc}"]) from None


def _stale_mirror_links(
    profile: Profile, root_descriptor: int, desired: set[Path]
) -> dict[Path, str]:
    stale: dict[Path, str] = {}
    for mirror in profile.skill_mirrors:
        handle = _open_parent(root_descriptor, mirror / ".loopzero-probe", create=False)
        if handle is None:
            continue
        try:
            for name in os.listdir(handle.descriptor):
                if name.startswith("."):
                    continue
                path = mirror / name
                metadata = os.stat(name, dir_fd=handle.descriptor, follow_symlinks=False)
                if stat.S_ISLNK(metadata.st_mode) and path not in desired:
                    stale[path] = os.readlink(name, dir_fd=handle.descriptor)
        except OSError as exc:
            raise ConfigError([f"skill mirror {mirror}: cannot inspect: {exc}"]) from None
        finally:
            os.close(handle.descriptor)
    return stale


def check(profile: Profile) -> list[Path]:
    """Return the paths whose checked-in content differs from the render."""
    with _locked_root(profile.root) as root_descriptor:
        if _partial_exists(root_descriptor):
            raise ConfigError(
                [f"interrupted sync: {PARTIAL_PATH} exists; run `loopzero sync` to recover"]
            )
        prepared = _prepare_from_fd(profile, root_descriptor)
        drift = [
            item.rendered.path
            for item in prepared
            if item.original != item.expected
            or item.original_symlink != item.rendered.symlink
        ]
        desired_links = {item.rendered.path for item in prepared if item.rendered.symlink}
        drift.extend(sorted(_stale_mirror_links(profile, root_descriptor, desired_links)))
        return drift


def _stage(item: Prepared, parent: DirectoryHandle) -> str:
    _verify_directory(parent)
    temporary = f".{item.rendered.path.name}.{secrets.token_hex(12)}"
    if item.rendered.symlink:
        try:
            os.symlink(os.fsdecode(item.expected), temporary, dir_fd=parent.descriptor)
        except BaseException:
            try:
                os.unlink(temporary, dir_fd=parent.descriptor)
            except FileNotFoundError:
                pass
            raise
        return temporary
    descriptor = -1
    try:
        descriptor = os.open(
            temporary,
            os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW | os.O_CLOEXEC,
            0o600,
            dir_fd=parent.descriptor,
        )
        os.fchmod(descriptor, item.original_mode if item.original_mode is not None else 0o644)
        offset = 0
        while offset < len(item.expected):
            offset += os.write(descriptor, item.expected[offset:])
        os.fsync(descriptor)
    except BaseException:
        if descriptor >= 0:
            os.close(descriptor)
        try:
            os.unlink(temporary, dir_fd=parent.descriptor)
        except FileNotFoundError:
            pass
        raise
    else:
        os.close(descriptor)
    return temporary


def _verify_reachable(root_descriptor: int, handle: DirectoryHandle) -> None:
    probe = _open_parent(root_descriptor, handle.relative / "probe", create=False)
    if probe is None:
        raise ConfigError([f"generated parent {handle.relative}: disappeared concurrently"])
    try:
        if probe.identity != handle.identity:
            raise ConfigError([f"generated parent {handle.relative}: changed concurrently"])
    finally:
        os.close(probe.descriptor)


def _verify_root_path(root: Path, root_descriptor: int) -> None:
    probe = _open_absolute_directory(root)
    try:
        if _identity(os.fstat(probe)) != _identity(os.fstat(root_descriptor)):
            raise ConfigError(["repository root changed concurrently"])
    finally:
        os.close(probe)


def write(profile: Profile) -> list[Path]:
    """Write every rendered file; return the paths that changed."""
    with _locked_root(profile.root) as root_descriptor:
        had_partial = _partial_exists(root_descriptor)
        prepared = _prepare_from_fd(profile, root_descriptor)
        changed = [
            item
            for item in prepared
            if item.original != item.expected
            or item.original_symlink != item.rendered.symlink
        ]
        desired_links = {item.rendered.path for item in prepared if item.rendered.symlink}
        stale_links = _stale_mirror_links(profile, root_descriptor, desired_links)
        partial_parent = _partial_handle(root_descriptor)
        if not changed and not stale_links:
            try:
                if had_partial:
                    _remove_partial(partial_parent)
                return []
            finally:
                os.close(partial_parent.descriptor)

        parents: dict[Path, DirectoryHandle] = {partial_parent.relative: partial_parent}
        staged: list[tuple[Prepared, DirectoryHandle, str]] = []
        try:
            for item in prepared:
                relative_parent = item.rendered.path.parent
                if relative_parent not in parents:
                    handle = _open_parent(root_descriptor, item.rendered.path, create=True)
                    assert handle is not None
                    parents[relative_parent] = handle
            for path in stale_links:
                if path.parent not in parents:
                    handle = _open_parent(root_descriptor, path, create=False)
                    assert handle is not None
                    parents[path.parent] = handle
            for item in changed:
                parent = parents[item.rendered.path.parent]
                staged.append((item, parent, _stage(item, parent)))

            # Re-read every render-time input through the anchored directory
            # descriptors. Honest concurrent syncs cannot enter this section
            # because they hold the same flock.
            _verify_root_path(profile.root, root_descriptor)
            for parent in parents.values():
                _verify_reachable(root_descriptor, parent)
            for item in prepared:
                state = _read_name(
                    parents[item.rendered.path.parent],
                    item.rendered.path.name,
                    item.rendered.path,
                    allow_symlink=item.rendered.symlink,
                )
                current = state.content if state is not None else None
                current_mode = state.mode if state is not None else None
                current_symlink = state.symlink if state is not None else False
                if (
                    current != item.original
                    or current_mode != item.original_mode
                    or current_symlink != item.original_symlink
                ):
                    raise ConfigError(
                        [f"{item.rendered.path}: changed concurrently; no files written"]
                    )
            current_stale = _stale_mirror_links(profile, root_descriptor, desired_links)
            if current_stale != stale_links:
                raise ConfigError(["skill mirror links changed concurrently; no files written"])

            _write_partial(partial_parent, changed, stale_links)
            for index, (item, parent, temporary) in enumerate(staged):
                _verify_directory(parent)
                try:
                    os.rename(
                        temporary,
                        item.rendered.path.name,
                        src_dir_fd=parent.descriptor,
                        dst_dir_fd=parent.descriptor,
                    )
                except OSError as exc:
                    raise ConfigError(
                        [
                            f"{item.rendered.path}: replacement failed; "
                            f"interrupted-sync marker retained: {exc}"
                        ]
                    ) from None
                os.fsync(parent.descriptor)
                staged[index] = (item, parent, "")
            for path in sorted(stale_links):
                parent = parents[path.parent]
                _verify_directory(parent)
                try:
                    os.unlink(path.name, dir_fd=parent.descriptor)
                    os.fsync(parent.descriptor)
                except OSError as exc:
                    raise ConfigError(
                        [
                            f"{path}: stale mirror removal failed; "
                            f"interrupted-sync marker retained: {exc}"
                        ]
                    ) from None
            _remove_partial(partial_parent)
            return [item.rendered.path for item in changed] + sorted(stale_links)
        finally:
            for _, parent, temporary in staged:
                if temporary:
                    try:
                        os.unlink(temporary, dir_fd=parent.descriptor)
                    except FileNotFoundError:
                        pass
            for parent in parents.values():
                os.close(parent.descriptor)
